[package]
name = "multikey-rs"
version = "0.1.0"
authors = ["Zyansheep <zyansheep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = "0.3.2"
elliptic-curve = "0.8.4"
rand = "0.8.1"
rsa = "0.3.0"
